### ISSUE TITLE
NameError: undefined method `proper_table_name' for class `Class'

### ISSUE THREAD

**Issue by hooverlunch** [jenseng/hair_trigger#49]
This method was moved to a different class in Rails 4.2.

https://github.com/rails/rails/pull/15512

Any plans for a fix? Or am I missing something?

**Comment by jenseng** [comment]
@hooverlunch can you provide a full stack trace? also which version of hairtrigger are you using?

as of hairtrigger v0.2.8, it *should* be using the correct class [for rails 4.1 and later](https://github.com/jenseng/hair_trigger/blob/5361d5118aa0a1996d8802209199bc5fdf0afa22/lib/hair_trigger.rb#L221:L225). maybe something else is going on with your setup?

**Comment by hooverlunch** [comment]
Sorry it's, um, been awhile...

I am using 0.2.20.

Here is the full backtrace:

```
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'hairtrigger'.
Gem Load Error is: undefined method `proper_table_name' for class `Class'
Backtrace for gem load error is:
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method_chain'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/hairtrigger-0.2.2/lib/hair_trigger/migrator.rb:9:in `singleton class'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/hairtrigger-0.2.2/lib/hair_trigger/migrator.rb:8:in `block in extended'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/hairtrigger-0.2.2/lib/hair_trigger/migrator.rb:7:in `class_eval'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/hairtrigger-0.2.2/lib/hair_trigger/migrator.rb:7:in `extended'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/hairtrigger-0.2.2/lib/hair_trigger.rb:197:in `extend'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/hairtrigger-0.2.2/lib/hair_trigger.rb:197:in `<top (required)>'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/hairtrigger-0.2.2/lib/hairtrigger.rb:1:in `<top (required)>'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
/Users/tomsmyth/code/elmo/config/application.rb:5:in `<top (required)>'
/Users/tomsmyth/code/elmo/Rakefile:4:in `require'
/Users/tomsmyth/code/elmo/Rakefile:4:in `<top (required)>'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/tomsmyth/.rbenv/versions/2.2.0/bin/rake:33:in `<top (required)>'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/Users/tomsmyth/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/Users/tomsmyth/.rbenv/versions/2.2.0/bin/bundle:23:in `load'
/Users/tomsmyth/.rbenv/versions/2.2.0/bin/bundle:23:in `<main>'
Bundler Error Backtrace:
/Users/tomsmyth/code/elmo/config/application.rb:5:in `<top (required)>'
/Users/tomsmyth/code/elmo/Rakefile:4:in `require'
/Users/tomsmyth/code/elmo/Rakefile:4:in `<top (required)>'
/Users/tomsmyth/.rbenv/versions/2.2.0/bin/bundle:23:in `load'
/Users/tomsmyth/.rbenv/versions/2.2.0/bin/bundle:23:in `<main>'
NameError: undefined method `proper_table_name' for class `Class'
/Users/tomsmyth/code/elmo/config/application.rb:5:in `<top (required)>'
/Users/tomsmyth/code/elmo/Rakefile:4:in `require'
/Users/tomsmyth/code/elmo/Rakefile:4:in `<top (required)>'
/Users/tomsmyth/.rbenv/versions/2.2.0/bin/bundle:23:in `load'
/Users/tomsmyth/.rbenv/versions/2.2.0/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```
