### ISSUE TITLE
Invalid PG version check in builder

### ISSUE THREAD

**Issue by onomated** [jenseng/hair_trigger#65]
Running current master branch with PG version 9.6.3, I get the following error during `db:migrate`:
```
HairTrigger::Builder::GenerationError: of can only be used in conjunction with nowrap on postgres 9.1 and greater
hair_trigger-52e88e4f623d/lib/hair_trigger/builder.rb:430:in `generate_trigger_postgresql'
hair_trigger-52e88e4f623d/lib/hair_trigger/builder.rb:230:in `generate'
hair_trigger-52e88e4f623d/lib/hair_trigger/builder.rb:347:in `maybe_execute'
hair_trigger-52e88e4f623d/lib/hair_trigger/builder.rb:155:in `set_nowrap'
hair_trigger-52e88e4f623d/lib/hair_trigger/builder.rb:145:in `nowrap'
20170807113627_create_triggers_events_insert_or_events_update.rb:20:in `up'
bin/rails:6:in `require'
```
`db_version < 91000` should be `db_version < 90100`

**Comment by jenseng** [comment]
Good catch, I'll push a fix 👍
